name: Sync to Hugging Face Spaces

on:
    push:
        branches:
            - main

jobs:
    sync:
        name: Sync
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Sync to Hugging Face Spaces
              uses: JacobLinCool/huggingface-sync@v1
              with:
                  github: ${{ secrets.GITHUB_TOKEN }}
                  user: jacoblincool # Hugging Face username or organization name
                  space: MP-SENet # Hugging Face space name
                  token: ${{ secrets.HF_TOKEN }} # Hugging Face token
                  configuration: headers.yaml
